//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditorGfd.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizacao_PT_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizacao_PT_BR() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditorGfd.Properties.Localizacao_PT_BR", typeof(Localizacao_PT_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pesquisar.
        /// </summary>
        internal static string BtnPesquisar {
            get {
                return ResourceManager.GetString("BtnPesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar propriedade.
        /// </summary>
        internal static string BtnSalvar {
            get {
                return ResourceManager.GetString("BtnSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Altura do caractere.
        /// </summary>
        internal static string DatagridColAltura {
            get {
                return ResourceManager.GetString("DatagridColAltura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Caractere.
        /// </summary>
        internal static string DatagridColCaractere {
            get {
                return ResourceManager.GetString("DatagridColCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código.
        /// </summary>
        internal static string DatagridColCodigo {
            get {
                return ResourceManager.GetString("DatagridColCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Correção X.
        /// </summary>
        internal static string DatagridColCorrecaoX {
            get {
                return ResourceManager.GetString("DatagridColCorrecaoX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Correção Y.
        /// </summary>
        internal static string DatagridColCorrecaoY {
            get {
                return ResourceManager.GetString("DatagridColCorrecaoY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id textura.
        /// </summary>
        internal static string DatagridColIdTextura {
            get {
                return ResourceManager.GetString("DatagridColIdTextura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Largura do caractere.
        /// </summary>
        internal static string DatagridColLargura {
            get {
                return ResourceManager.GetString("DatagridColLargura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Largura do glifo.
        /// </summary>
        internal static string DatagridColLgGlifo {
            get {
                return ResourceManager.GetString("DatagridColLgGlifo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Largura máxima do glifo.
        /// </summary>
        internal static string DatagridColMaxLgGlifo {
            get {
                return ResourceManager.GetString("DatagridColMaxLgGlifo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arquivos .gfd (*.gfd)|*.gfd.
        /// </summary>
        internal static string FiltroOpf {
            get {
                return ResourceManager.GetString("FiltroOpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Altura.
        /// </summary>
        internal static string LbAltura {
            get {
                return ResourceManager.GetString("LbAltura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Base.
        /// </summary>
        internal static string LbBase {
            get {
                return ResourceManager.GetString("LbBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Caractere.
        /// </summary>
        internal static string LbCaractere {
            get {
                return ResourceManager.GetString("LbCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Correção relativa Eixo X.
        /// </summary>
        internal static string LbCorecaoX {
            get {
                return ResourceManager.GetString("LbCorecaoX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Correção relativa Eixo Y.
        /// </summary>
        internal static string LbCorecaoY {
            get {
                return ResourceManager.GetString("LbCorecaoY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descendente.
        /// </summary>
        internal static string LbDescendente {
            get {
                return ResourceManager.GetString("LbDescendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Largura.
        /// </summary>
        internal static string LbLargura {
            get {
                return ResourceManager.GetString("LbLargura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Largura do glifo.
        /// </summary>
        internal static string LbLarguraGlifo {
            get {
                return ResourceManager.GetString("LbLarguraGlifo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Altura do Caractere.
        /// </summary>
        internal static string LbLeAltura {
            get {
                return ResourceManager.GetString("LbLeAltura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Largura do caractere.
        /// </summary>
        internal static string LbLeLargura {
            get {
                return ResourceManager.GetString("LbLeLargura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Largura do glifo.
        /// </summary>
        internal static string LbLeLarguraGlifo {
            get {
                return ResourceManager.GetString("LbLeLarguraGlifo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Linha base.
        /// </summary>
        internal static string LbLeLinhaBase {
            get {
                return ResourceManager.GetString("LbLeLinhaBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Linha descendente.
        /// </summary>
        internal static string LbLeLinhaDesc {
            get {
                return ResourceManager.GetString("LbLeLinhaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Prévia in game.
        /// </summary>
        internal static string LbPrevia {
            get {
                return ResourceManager.GetString("LbPrevia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar modificações.
        /// </summary>
        internal static string LbSalvarGfd {
            get {
                return ResourceManager.GetString("LbSalvarGfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Propriedades de caracteres.
        /// </summary>
        internal static string LbTitulo {
            get {
                return ResourceManager.GetString("LbTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editor de propriedades.
        /// </summary>
        internal static string LbTituloEditorProp {
            get {
                return ResourceManager.GetString("LbTituloEditorProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arquivo salvo em:.
        /// </summary>
        internal static string MensagemArquivoSalvo {
            get {
                return ResourceManager.GetString("MensagemArquivoSalvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione a pasta contenha os seguintes arquivos png:.
        /// </summary>
        internal static string MensagemAvisoDeTexturas {
            get {
                return ResourceManager.GetString("MensagemAvisoDeTexturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar gfd sem salvar as modificações?.
        /// </summary>
        internal static string MensagemAvisoFechar {
            get {
                return ResourceManager.GetString("MensagemAvisoFechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja sair sem salvar as modificações?.
        /// </summary>
        internal static string MensagemAvisoSair {
            get {
                return ResourceManager.GetString("MensagemAvisoSair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo de caractere não pode estar vazio..
        /// </summary>
        internal static string MensagemCampoVazio {
            get {
                return ResourceManager.GetString("MensagemCampoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação cancelada..
        /// </summary>
        internal static string MensagemCancelaOp {
            get {
                return ResourceManager.GetString("MensagemCancelaOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O caractere já está presente na lista..
        /// </summary>
        internal static string MensagemCaracJaExiste {
            get {
                return ResourceManager.GetString("MensagemCaracJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Caractere.
        /// </summary>
        internal static string MensagemCaracNaoEncoPt1 {
            get {
                return ResourceManager.GetString("MensagemCaracNaoEncoPt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível salvar o arquivo no seguinte diretório:.
        /// </summary>
        internal static string MensagemErroSalvar {
            get {
                return ResourceManager.GetString("MensagemErroSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Versão de gfd não suportado..
        /// </summary>
        internal static string MensagemGfdNaoSuportado {
            get {
                return ResourceManager.GetString("MensagemGfdNaoSuportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a não encontrado..
        /// </summary>
        internal static string MensagemNaoEcontrado {
            get {
                return ResourceManager.GetString("MensagemNaoEcontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação necessária:.
        /// </summary>
        internal static string MensagemOp {
            get {
                return ResourceManager.GetString("MensagemOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foram encontrados os seguintes arquivos png:.
        /// </summary>
        internal static string MensagemTexturasNãoEncontradas {
            get {
                return ResourceManager.GetString("MensagemTexturasNãoEncontradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aviso!.
        /// </summary>
        internal static string TituloAviso {
            get {
                return ResourceManager.GetString("TituloAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editor de GFD.
        /// </summary>
        internal static string TituloDoForm {
            get {
                return ResourceManager.GetString("TituloDoForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro!.
        /// </summary>
        internal static string TituloErro {
            get {
                return ResourceManager.GetString("TituloErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abrir arquivo .gfd.
        /// </summary>
        internal static string TsAbrirGfd {
            get {
                return ResourceManager.GetString("TsAbrirGfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editor de GFD v0.5 por Matheus Abreu.
        /// </summary>
        internal static string TsEdtGFDSobre {
            get {
                return ResourceManager.GetString("TsEdtGFDSobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar .gfd.
        /// </summary>
        internal static string TSFecharGfd {
            get {
                return ResourceManager.GetString("TSFecharGfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gfd.
        /// </summary>
        internal static string TsGfd {
            get {
                return ResourceManager.GetString("TsGfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobre.
        /// </summary>
        internal static string TSSobre {
            get {
                return ResourceManager.GetString("TSSobre", resourceCulture);
            }
        }
    }
}
