//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditorGfd.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizacao_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizacao_EN() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditorGfd.Properties.Localizacao_EN", typeof(Localizacao_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Search.
        /// </summary>
        internal static string BtnPesquisar {
            get {
                return ResourceManager.GetString("BtnPesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save properties.
        /// </summary>
        internal static string BtnSalvar {
            get {
                return ResourceManager.GetString("BtnSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Char height.
        /// </summary>
        internal static string DatagridColAltura {
            get {
                return ResourceManager.GetString("DatagridColAltura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Character.
        /// </summary>
        internal static string DatagridColCaractere {
            get {
                return ResourceManager.GetString("DatagridColCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Code.
        /// </summary>
        internal static string DatagridColCodigo {
            get {
                return ResourceManager.GetString("DatagridColCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a X Correction.
        /// </summary>
        internal static string DatagridColCorrecaoX {
            get {
                return ResourceManager.GetString("DatagridColCorrecaoX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Y Correction.
        /// </summary>
        internal static string DatagridColCorrecaoY {
            get {
                return ResourceManager.GetString("DatagridColCorrecaoY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Texture ID.
        /// </summary>
        internal static string DatagridColIdTextura {
            get {
                return ResourceManager.GetString("DatagridColIdTextura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Char width.
        /// </summary>
        internal static string DatagridColLargura {
            get {
                return ResourceManager.GetString("DatagridColLargura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Glyph width.
        /// </summary>
        internal static string DatagridColLgGlifo {
            get {
                return ResourceManager.GetString("DatagridColLgGlifo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Glyph max width.
        /// </summary>
        internal static string DatagridColMaxLgGlifo {
            get {
                return ResourceManager.GetString("DatagridColMaxLgGlifo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .gfd files(*.gfd)|*.gfd.
        /// </summary>
        internal static string FiltroOpf {
            get {
                return ResourceManager.GetString("FiltroOpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Height.
        /// </summary>
        internal static string LbAltura {
            get {
                return ResourceManager.GetString("LbAltura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Baseline.
        /// </summary>
        internal static string LbBase {
            get {
                return ResourceManager.GetString("LbBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Character.
        /// </summary>
        internal static string LbCaractere {
            get {
                return ResourceManager.GetString("LbCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a X Correction.
        /// </summary>
        internal static string LbCorecaoX {
            get {
                return ResourceManager.GetString("LbCorecaoX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Y Correction.
        /// </summary>
        internal static string LbCorecaoY {
            get {
                return ResourceManager.GetString("LbCorecaoY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Downline.
        /// </summary>
        internal static string LbDescendente {
            get {
                return ResourceManager.GetString("LbDescendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Width.
        /// </summary>
        internal static string LbLargura {
            get {
                return ResourceManager.GetString("LbLargura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Glyph width.
        /// </summary>
        internal static string LbLarguraGlifo {
            get {
                return ResourceManager.GetString("LbLarguraGlifo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Char height.
        /// </summary>
        internal static string LbLeAltura {
            get {
                return ResourceManager.GetString("LbLeAltura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Char width.
        /// </summary>
        internal static string LbLeLargura {
            get {
                return ResourceManager.GetString("LbLeLargura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Glyph width.
        /// </summary>
        internal static string LbLeLarguraGlifo {
            get {
                return ResourceManager.GetString("LbLeLarguraGlifo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Baseline.
        /// </summary>
        internal static string LbLeLinhaBase {
            get {
                return ResourceManager.GetString("LbLeLinhaBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Downline.
        /// </summary>
        internal static string LbLeLinhaDesc {
            get {
                return ResourceManager.GetString("LbLeLinhaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a In game preview.
        /// </summary>
        internal static string LbPrevia {
            get {
                return ResourceManager.GetString("LbPrevia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save changes.
        /// </summary>
        internal static string LbSalvarGfd {
            get {
                return ResourceManager.GetString("LbSalvarGfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Char properties table.
        /// </summary>
        internal static string LbTitulo {
            get {
                return ResourceManager.GetString("LbTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Properties Editor.
        /// </summary>
        internal static string LbTituloEditorProp {
            get {
                return ResourceManager.GetString("LbTituloEditorProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Files saved in:.
        /// </summary>
        internal static string MensagemArquivoSalvo {
            get {
                return ResourceManager.GetString("MensagemArquivoSalvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select the folder containing the following png files:.
        /// </summary>
        internal static string MensagemAvisoDeTexturas {
            get {
                return ResourceManager.GetString("MensagemAvisoDeTexturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close gfd without saving?.
        /// </summary>
        internal static string MensagemAvisoFechar {
            get {
                return ResourceManager.GetString("MensagemAvisoFechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Leave without saving?.
        /// </summary>
        internal static string MensagemAvisoSair {
            get {
                return ResourceManager.GetString("MensagemAvisoSair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The character field cannot be empty..
        /// </summary>
        internal static string MensagemCampoVazio {
            get {
                return ResourceManager.GetString("MensagemCampoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelled.
        /// </summary>
        internal static string MensagemCancelaOp {
            get {
                return ResourceManager.GetString("MensagemCancelaOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The character is already present in the list..
        /// </summary>
        internal static string MensagemCaracJaExiste {
            get {
                return ResourceManager.GetString("MensagemCaracJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Char.
        /// </summary>
        internal static string MensagemCaracNaoEncoPt1 {
            get {
                return ResourceManager.GetString("MensagemCaracNaoEncoPt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to save the file in the following directory:.
        /// </summary>
        internal static string MensagemErroSalvar {
            get {
                return ResourceManager.GetString("MensagemErroSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unsupported gfd version..
        /// </summary>
        internal static string MensagemGfdNaoSuportado {
            get {
                return ResourceManager.GetString("MensagemGfdNaoSuportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a not found..
        /// </summary>
        internal static string MensagemNaoEcontrado {
            get {
                return ResourceManager.GetString("MensagemNaoEcontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mandatory:.
        /// </summary>
        internal static string MensagemOp {
            get {
                return ResourceManager.GetString("MensagemOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The following pngs weren&apos;t found:.
        /// </summary>
        internal static string MensagemTexturasNãoEncontradas {
            get {
                return ResourceManager.GetString("MensagemTexturasNãoEncontradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Warning.
        /// </summary>
        internal static string TituloAviso {
            get {
                return ResourceManager.GetString("TituloAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GFD Editor.
        /// </summary>
        internal static string TituloDoForm {
            get {
                return ResourceManager.GetString("TituloDoForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error!.
        /// </summary>
        internal static string TituloErro {
            get {
                return ResourceManager.GetString("TituloErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Open .gfd file.
        /// </summary>
        internal static string TsAbrirGfd {
            get {
                return ResourceManager.GetString("TsAbrirGfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GFD by Matheus Abreu.
        /// </summary>
        internal static string TsEdtGFDSobre {
            get {
                return ResourceManager.GetString("TsEdtGFDSobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close .gfd file.
        /// </summary>
        internal static string TSFecharGfd {
            get {
                return ResourceManager.GetString("TSFecharGfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gfd.
        /// </summary>
        internal static string TsGfd {
            get {
                return ResourceManager.GetString("TsGfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a About.
        /// </summary>
        internal static string TSSobre {
            get {
                return ResourceManager.GetString("TSSobre", resourceCulture);
            }
        }
    }
}
